spring.application.name=object-storage
server.port=8080
spring.cassandra.contact-points=127.0.0.1:9044,127.0.0.1:9045
spring.cassandra.port=9044
spring.cassandra.local-datacenter=dc1
spring.cassandra.keyspace-name=object_storage
spring.cassandra.schema-action=create_if_not_exists

spring.cassandra.request.consistency=local_quorum

object.storage.root-folder=