spring.application.name=object-storage

server.port=${SERVER_PORT}
spring.cassandra.contact-points=${SPRING_CASSANDRA_CONTACT_POINTS}
spring.cassandra.local-datacenter=${SPRING_CASSANDRA_LOCAL_DATACENTER}
spring.cassandra.keyspace-name=${SPRING_CASSANDRA_KEYSPACE_NAME}
spring.cassandra.schema-action=${SPRING_CASSANDRA_SCHEMA_ACTION}

spring.cassandra.request.consistency=${SPRING_CASSANDRA_REQUEST_CONSISTENCY}
spring.cassandra.username=${SPRING_CASSANDRA_USERNAME}
spring.cassandra.password=${SPRING_CASSANDRA_PASSWORD}
object.storage.root-folder=${OBJECT_STORAGE_ROOT_FOLDER}